### ISSUE TITLE
Support 'auto' firmware

### ISSUE THREAD

**Issue by ES-Alexander** [bluerobotics/ping-arduino#29]
Currently this library doesn't support our latest firmware (`Ping_V3.28_auto.hex`), so users wanting to use Software serial generally need to downgrade their firmware to get it working, or use 115200 baud at the risk of communication reliability issues.

- [x] @patrickelectric has mentioned it should just require sending alternating `10101010...` for a while on startup, if the baud isn't 115200. Not sure if this only handles 9600 or if it's also possible to use other bauds in between. 

- [x] If production doesn't already flash and ship with 3.28 then that should be changed.

This should reduce issues like #27 and #19, and other similar problems from people not reading or understanding our [Ping with Arduino guide](https://bluerobotics.com/learn/using-the-ping-sonar-with-an-arduino/#change-the-baudrate-to-9600).

- [x] Once this is complete we should update that guide and our example code and docs to be more clear that 9600 baud is _recommended_ for Software Serial, and other bauds are possible but "at user's risk", unless using Hardware Serial, in which case 115200 should work without issues.

**Comment by ES-Alexander** [comment]
> @patrickelectric has mentioned it should just require sending alternating 10101010... for a while on startup, if the baud isn't 115200. Not sure if this only handles 9600 or if it's also possible to use other bauds in between.

Have confirmed that this approach works. Only 115200 and 9600 baudrates are valid, and baudrate can only be set on first connection after device startup (changing baudrate after communication has already been established requires power-cycling the device).

**Comment by patrickelectric** [comment]
It's a great start, we can check higher baudrates in future issues. 
IIRC it was requested to move to 3.28 a long time ago, I'll check.
