### ISSUE TITLE
Ping sensor hardware serial

### ISSUE THREAD

**Issue by ReyPsico** [bluerobotics/ping-arduino#42]
I was trying to use hardware serial of arduino with ping sensor, bcos i cant use software serial.
The problem is, i cant make the Ping1D object as global. i can only create the Ping1D object with a reference to the Serial object inside the setup(). so it cant be used in loop(). How do i solve this problem?

**Comment by patrickelectric** [comment]
Hi,

Can you please provide a minimal example that replicates your problem ?
